name: ci-test

on:
  push:
    branches-ignore:
      - docker

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      # Install node modules
      - run: npm ci

      # Run all unit tests
      - run: npm run ci-test
